"""update user model

Revision ID: c91c333f162b
Revises: 53c52bd9cf6c
Create Date: 2026-04-08 16:54:10.232959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c91c333f162b"
down_revision: Union[str, Sequence[str], None] = "53c52bd9cf6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("refresh_token", sa.String(length=512), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "refresh_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token_expires_at")
    op.drop_column("users", "refresh_token")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
