"""update request model

Revision ID: 08be960c5ba0
Revises: c91c333f162b
Create Date: 2026-04-08 18:35:00.092284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "08be960c5ba0"
down_revision: Union[str, Sequence[str], None] = "c91c333f162b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("title", sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "title")
    # ### end Alembic commands ###
